@startuml
hide circle
hide empty methods

class 注文{
    合計
}

class 注文明細{
    数量
    小計
}

class 割引クーポン{
    値引き額
    期限
}

class 商品{
    名称
    単価
}

class カップ{
    サイズ
}

class ドリンク{
    種別
}

class 材料{

}
class ハンバーガー{
    種別
}

class ポテト{
    サイズ
}


hide empty fields

class フード{

}

class レシピ{

}

class パン{

}

class 肉{

}

class 野菜{

}

class チーズ{

}
注文 "1..*" o-  注文明細
注文明細 "0..*"-"0..1" 割引クーポン
注文明細 "0..*"--"1" 商品
カップ -|> 商品
ドリンク "1..3"-"0..*" カップ 
フード "1"-"1" レシピ
商品 <|-- フード
フード <|-- ハンバーガー
フード <|-- ポテト
材料 "1..*" -o "1..*" ハンバーガー
材料 <|-- パン 
材料 <|-- 肉
材料 <|-- 野菜
材料 <|-- チーズ
@enduml