@startuml
left to right direction
[*] --> 電源SWON
電源SWON --> 右旋回 :システム起動
電源SWON --> 左旋回 :システム起動
右旋回 --> 左旋回 :光センサーがラインを外れると、「明るい」と判断する
左旋回 --> 右旋回 :光センサーが黒いライン上にあると、「暗い」と判断する
右旋回 --> 電源SWOFF :システム停止
左旋回 --> 電源SWOFF :システム停止
電源SWOFF --> [*]
@enduml