@startuml 診察予約システム
left to right direction
[*] --> メニュー
メニュー --> [*]
メニュー  --> 予約と確認 :予約する
メニュー --> 今の順番 :現在診療中の患者の順番を表示する
今の順番 --> メニュー : 現在の患者番号を一つ増やす
あなたの順番 --> メニュー : 登録者番号を表示する
予約と確認 --> メニュー :取り消しボタンを押す
予約と確認 --> あなたの順番 : 登録ボタンを押す
予約と確認 --> あなたの順番 : 確認ボタンを押す

@enduml
